function concatenateAllFunctions()
%Concatenates all functions in "source" folder into a single file.
%
% Author: Matt Dvorsky

%% Inputs
outputFilename = "allFiles.txt";

%% Get All ".m" Files
fileList = dir(fullfile("source", "**", "*.m"));

fileNameSeparator = "------------------------------------" + ...
    "---------------------------------------";

%% Read All Files
fileContents = strings(2, numel(fileList));
for ii = 1:numel(fileList)
    fileContents(1, ii) = sprintf("%s%s%s%sFile: '%s'%s%s%s%s", ...
        newline(), ...
        newline(), ...
        fileNameSeparator, ...
        newline(), ...
        fileList(ii).name, ...
        newline(), ...
        fileNameSeparator, ...
        newline(), ...
        newline());
    fileContents(2, ii) = string(fileread(fullfile(...
        fileList(ii).folder, ...
        fileList(ii).name)));
end

%% Write to Output File
fileOutStr = strjoin(fileContents(:), "");
writelines(fileOutStr, outputFilename);

end