function [plotAxis, structureTextHandle] = setupPlotPanel(plotPanel, numLayers)
%Set up structure string axis and text.
% This is for nLayerViewer.
% 
% Author: Matt Dvorsky

arguments
    plotPanel(1, 1) matlab.ui.container.Panel;
    numLayers(1, 1) {mustBePositive, mustBeInteger};
end

%% Setup Structure String Axis
structureStringAxisSize = 0.1 + 0.1*numLayers;

structureStringAxis = axes(plotPanel, ...
    Position=[0, 0, 1, structureStringAxisSize], ...
    TickLength=[0, 0], ...
    XTick={}, YTick={}, ...
    Color="none", ...
    XColor="none", ...
    YColor="none");

%% Create Text Object
structureTextHandle = text(structureStringAxis, ...
    0.5, 0.5, "", ...
    Units="normalized", ...
    HorizontalAlignment="center", ...
    FontName="Monospaced", ...
    FontWeight="bold", ...
    FontSize=9);

%% Setup Polar Plot Axis
plotAxisPosition = [0.048, 0.03, 0.9, 0.9];
plotAxisPosition(2) = 1 - (1 - plotAxisPosition(2)) ...
    .* (1 - structureStringAxisSize);
plotAxisPosition(4) = plotAxisPosition(4) ...
    .* (1 - structureStringAxisSize);

plotAxis = axes(plotPanel, ...
    Position=plotAxisPosition, ...
    Box="on");

end