function [plotPanel, sliderPanels] = setupFigureAndPanels(...
    fig, figSize, plotPanelWidth, fontSize)
%Setup nLayerViewer figure and panels for the plot and structure sliders.
% This is for nLayerViewer.
% 
% Author: Matt Dvorsky

arguments
    fig(1, 1) matlab.ui.Figure;
    figSize(1, :);
    plotPanelWidth(1, 1);
    fontSize(1, 1);
end

%% Setup Figure
clf(fig);
fig.Units = "normalized";
fig.Position = figSize;
fig.ToolBar = "none";

%% Create Panel for Plot
plotPanel = uipanel(fig, ...
    Position=[0, 0, plotPanelWidth, 1]);

%% Create Structure Slider Panels
sliderPanel = uipanel(fig, ...
    Position=[plotPanelWidth, 0, 1 - plotPanelWidth, 1]);

erpPanel = uipanel(sliderPanel, Position=[0, 4/5, 1, 1/5], ...
    Tag="erp", ...
    FontSize=fontSize, ...
    Title="Dielectric Constant (erp)");

erTanPanel = uipanel(sliderPanel, Position=[0, 3/5, 1, 1/5], ...
    Tag="erTanD", ...
    FontSize=fontSize, ...
    Title="Dielectric Loss Tangent (erpp/erp)");

urpPanel = uipanel(sliderPanel, Position=[0, 2/5, 1, 1/5], ...
    Tag="urp", ...
    FontSize=fontSize, ...
    Title="Magnetic Constant (urp)");

urTanPanel = uipanel(sliderPanel, Position=[0, 1/5, 1, 1/5], ...
    Tag="urTanD", ...
    FontSize=fontSize, ...
    Title="Magnetic Loss Tangent (urpp/urp)");

thkPanel = uipanel(sliderPanel, Position=[0, 0, 1, 1/5], ...
    Tag="thk", ...
    FontSize=fontSize, ...
    Title="Thickness (mm)");

sliderPanels = {erpPanel, erTanPanel, urpPanel, urTanPanel, thkPanel};

end
